/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as hexaFinityTokenUpgradableSol from "./HexaFinityTokenUpgradable.sol";
export type { hexaFinityTokenUpgradableSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as libraries from "./libraries";
export type { libraries };
import type * as test from "./test";
export type { test };
export type { HexaFinityToken } from "./HexaFinityToken";
